version: '2'
services:
    pip-app:
        image: pip
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pip-mysql:3306/pip?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=pip-elasticsearch:9300
        ports:
            - 8080:8080
    pip-mysql:
        extends:
            file: mysql.yml
            service: pip-mysql
    pip-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pip-elasticsearch
